# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: packaging/leapp-repository.spec

actions:
  create-archive:
  - rm -f packaging/deps-pkgs.tar.gz
  - make source
  - bash -c "mv packaging/sources/deps-pkgs.tar.gz packaging/"
  - bash -c "mv packaging/sources/leapp-repository-*.tar.gz packaging/"
  # packit requires this information even though it's not utilized
  # given the fix-spec-file action being set
  - bash -c "ls -1 packaging/leapp-repository-*.tar.gz"
  fix-spec-file:
  - bash -c "echo PACKIT_PROJECT_VERSION=${PACKIT_PROJECT_VERSION}"
  - bash -c "sed -i -r \"s/Release:(\s*)\S+/Release:\1${PACKIT_RPMSPEC_RELEASE}%{?dist}/\" packaging/leapp-repository.spec"

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: leapp-repository
# downstream (Fedora) RPM package name
downstream_package_name: leapp-repository

upstream_tag_template: 'v{version}'
