# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: packaging/leapp-repository.spec

actions:
  create-archive:
  - rm -f packaging/deps-pkgs.tar.gz
  - make source
  - find packaging/sources/ -type f

# name in upstream package repository/registry (e.g. in PyPI)
upstream_package_name: leapp-repository
# downstream (Fedora) RPM package name
downstream_package_name: leapp-repository

upstream_tag_template: 'v{version}'
